[package]
name = "fft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "0.5.0"
plotters = "^0.3.1"
num = "0.4.0"
rand_distr = "0.4.3"
rand = "0.8.5"
